@echo off
echo Building Java backend...
call mvn clean package

echo Starting Java backend...
start /b java -jar target\p2p-1.0-SNAPSHOT.jar

echo Waiting for backend to start...
timeout /t 3

echo Checking if node_modules exists...
if not exist client\node_modules (
    echo Installing frontend dependencies...
    cd client && npm install && cd ..
)

echo Starting frontend...
cd client && npm run dev

echo Stopping backend...
taskkill /f /im java.exe
